name: "Docker: build container"

on:
  workflow_call:
    inputs:
      docker-file:
        description: "Path to the docker file"
        type: string
        required: true
      working-directory:
        description: "Build context"
        type: string
        required: true
      acr-name:
        description: "Container registry name"
        type: string
        required: true
      container-tags:
        description: "Container tags"
        type: string
        required: true

    secrets:
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_CLIENT_ID:
        required: true

jobs:
  build-and-push-container:
    name: Docker build and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Az CLI login
        uses: azure/login@v1
        with:
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}

      - name: Login to container registry
        run: |
          az acr login --name ${{ inputs.acr-name }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ${{ inputs.docker-file }}
          context: ${{ inputs.working-directory }}
          push: true
          tags: ${{ inputs.container-tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
